openapi: '3.0.2'
info:
  title: Santander Meetups Challenge API
  version: '1.0'

servers:
  - url: https://localhost:5000/api
    description: Default local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
  schemas:
    Meetup:
      type: object
      required:
        - id
          name
          date
          numPeople
      properties:
        id:
          type: integer
          example: 15
        name:
          type: string
          example: My meetup
        date:
          type: string
          example: "2021-05-15"
        numPeople:
          type: integer
          example: 10
        estimatedBeerPacks:
          type: integer
          example: 2
        tempInCelsius:
          type: number
          example: 14.5
    WeatherForecast:
      type: object
      required:
        - date
          temp
      properties:
        date:
          type: string
          example: "2021-05-13"
        temp:
          type: number
          description: Temperature in °C
          example: 19.4
    BeersForecast:
      allOf:
        - $ref: '#/components/schemas/WeatherForecast'
      required:
        - beerPacks
      properties:
        beerPacks:
          type: integer
          example: 3

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      summary: Authenticates the user against the DB credentials
      tags:
        - Auth
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: A JWT with user data as payload
          content:
            text/plain:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMTcxMjc2OCwiZXhwIjoxNjIxNzEzNjY4fQ.YkncdxSnVmsRMsd1pq7S7dZkRjmYTuG2u1w9hTZd4ec
        '400':
          description: Invalid credentials
  
  /beers/forecast:
    get:
      summary: Returns a forecast with the number of 6 packs estimated
      tags:
        - Beers
      parameters:
        - in: query
          name: date
          description: Planned date for meetup
          schema:
            type: string
          required: true
        - in: query
          name: people
          description: Number of estimated attendees
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Forecast for weather and estimated beer packs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeersForecast'
        '400':
          description: Bad request
        '404':
          description: No forecast available for this date

  /meetups:
    post:
      tags:
        - Meetups
      summary: Creates new meetup
      responses:
        '201':
          description: "Meetup created"
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Meetup'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

  /meetups/upcoming:
    get:
      summary: Returns upcoming meetups
      tags:
        - Meetups
      responses:
        '200':
          description: "List of upcoming meetups returned"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meetup'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

  /meetups/upcoming/:id/subscribe:
    post:
      summary: Subscribes to specified meetup
      tags:
        - Meetups
      responses:
        '201':
          description: "Subscription registered"
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Meetup'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"
    delete:
      summary: Unsubscribes from specified meetup
      tags:
        - Meetups
      responses:
        '200':
          description: "Unsubscribe successful"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meetup'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

  /meetups/past:
    get:
      summary: Returns past meetups
      tags:
        - Meetups
      responses:
        '200':
          description: "List of upcoming meetups returned"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meetup'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

  /meetups/past/:id/check-in:
    post:
      summary: Checks in to specified meetup
      tags:
        - Meetups
      responses:
        '201':
          description: "Check in successful"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meetup'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"
    delete:
      summary: Checks out from specified meetup
      tags:
        - Meetups
      responses:
        '200':
          description: "Check out successful"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meetup'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

  /weather/forecasts:
    get:
      summary: Retrieves a list of weather forecasts
      tags:
        - Weather
      responses:
        '200':
          description: "Forecasts returned"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"

  /weather/cache:
    post:
      summary: Refreshes forecasts cache
      tags:
        - Weather
      responses:
        '201':
          description: "Cache refreshed"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
        '400':
          description: "Bad request"
        '401':
          description: "Unauthorized"